workflows:
 
  build-ios:
    name: Build iOS
    environment:
      vars:
        FLUTTER_CHANNEL: stable
        FLUTTER_VERSION: latest
    scripts:
      - flutter packages get
      - flutter build ios --release

buildscript {
  repositories {
    // Make sure that you have the following two repositories
    google()  // Google's Maven repository
    mavenCentral()  // Maven Central repository
  }

  dependencies {
      ...
      classpath("com.android.tools.build:gradle:7.2.0")

      // Make sure that you have the Google services Gradle plugin dependency
      classpath("com.google.gms:google-services:4.3.15")

      // Add the dependency for the App Distribution Gradle plugin
      classpath("com.google.firebase:firebase-appdistribution-gradle:4.0.0")
  }
}
