{
  "workflows": {
    "version": any,
    "build-ios": {
      "name": "Build iOS",
      "environment": {
        "vars": {
          "FLUTTER_CHANNEL": "stable",
          "FLUTTER_VERSION": "latest"
        }
      },
      "scripts": [
        "flutter packages get",
        "flutter build ios --release"
      ]
    }
  }
}
