# codemagic.yaml

workflows:
  # Define your workflow name
  ios_build_workflow:
    name: iOS Build Workflow
    # Specify the trigger for the workflow, for example, on push to the master branch
    trigger:
      - "push"
    # Define the build environment and settings
    environment:
      flutter: "2.0.0"  # Specify your Flutter version
      xcode: "13.0"     # Specify the Xcode version
    # Define the build script
    scripts:
      # Set up the Flutter environment
      - name: Install Flutter Dependencies
        script: flutter pub get
      # Build the iOS app in release mode
      - name: Build iOS Release
        script: flutter build ios --release
    # Define the artifacts you want to save or deploy
    artifacts:
      # Save the iOS build artifacts
      - build/ios/
    # Define deployment steps (optional)
    deployment:
      # Specify your deployment provider (e.g., App Store Connect)
      - provider: app-store-connect
        # Add your API key, app identifier, and other necessary configurations
        api_key: $APP_STORE_CONNECT_API_KEY
        app_identifier: com.example.myapp
