workflows:
  primary:
    name: Build and Test
    environment:
      flutter: latest
    scripts:
      - name: Install Dependencies
        script: flutter pub get

      - name: Build iOS Release
        script: flutter build ios --release

    artifacts:
      - build/ios/Release.ipa

    publishing:
      email:
        recipients:
          - allbstanje@gmail.com
        subject: "CodeMagic Build Finished"
        message: "The build of your iOS app is complete. You can download the IPA file here: $BUILD_DIR/build/ios/Release.ipa"
